sudo: false
language: python
install:
- pip install mkdocs==1.1.2
- pip install mkdocs-material==6.1.0
- pip install mkdocs-macros-plugin pymdown-extensions==8.0 mkdocs-markdownextradata-plugin mkdocs-minify-plugin mkdocs-material-extensions==1.0.1
script:
- git clean -f -d -x;
- mkdocs build
deploy:
    provider: script
    script: if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./deploy.sh; else echo "PR skip deploy"; fi
    on:
      branch: maste

env:
  matrix:
    secure: Tmpg90RkoquseHL66sGvj0Q5u8tjD4201adzeg9z2tscmdGsHp+CUGvY0dy0jYUv9cWIYdTj9s5Ctd/3IxlKjzjyoWDzlefeGOkr7fL5nf3F9wDmynQMEDUB7a1bpCtNtcd31ZbyBYN44OBfnrqgZavAeCqQgE4jcOpnuXoTYktkMV1661tUPLlBiwe2AtT7JUE/WscGlVCYYpXFo8XUvgmMIZE2kmfDKR0lsjYfJ3QUPrZ7Kq4wknzKmZuYoHb5wB4N9cednth8iAWe4lNCKvFkDXLC9KDg5Vhi0g/zk4eB7Ww/qCCEXt6l+D80OeT+x0eWVaR1NOmsktn/X/yr8s17CvOTfEJ73Bsq3jD/nub7xFnn5SCewndMSYgZjDOLIAu5PLfKdUpXRQu9kXYM+VRut4g6qL2h1t09zkxuf6KZ5QGkuW3pZTidOgoL0CEIkIwT3a7+gzLlYUZJHsO3VrmScSmua3Ip4wixKgLhb4BD4fibHYuU97hW9ueGU7gUIJKZNc0Sm0hfUd5mRkN7trNgoZ7FZ1xPDXqj2Xa6sQDiJiJOPIhBWQzRb9baumhUDwrjOJzGIvQfOWQPRVS6dcgh/XZkafALST5xhOdTy63OkelzAKndXeMkB9C3gxMUs4qwWf6vxMVFqeE7NxAgXtLDd43Ofut9xL7FX58CnaI=
